name: Build Source Distribution

on:
  workflow_dispatch:

jobs:
  build-sdist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV
        run: |
          curl -fsSL https://github.com/astral-sh/uv/releases/latest/download/uv-installer.sh | sh

      - name: Create UV Virtual Environment
        run: |
          uv venv .venv

      - name: Install Build Tools via UV
        run: |
          uv pip install --upgrade setuptools build

      - name: Lock Dependencies (optional)
        run: |
          uv lock

      - name: Sync to Locked Dependencies
        run: |
          uv sync --locked

      - name: Build Source Distribution (sdist)
        run: |
          python -m build --sdist

      - name: Upload sdist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
