name: Build sdist with uv

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build-sdist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Generate uv.lock if missing
        run: |
          if [ ! -f uv.lock ]; then
            uv pip compile --generate-hashes
          fi

      - name: Create and activate virtualenv, install dependencies
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -r uv.lock
          uv pip install build

      - name: Build sdist
        run: |
          source .venv/bin/activate
          python -m build --sdist

      - name: Upload sdist artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
