name: Update version

on: [push]

permissions:
  contents: write
  actions: read

jobs:
  Change-version:
    runs-on: ubuntu-latest

    env:
      OLD_VERSION: '2025.01.29'
      NEW_VERSION: '2025.06.16'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all tags
    - name: Replace version number
      run: |
          ls        
          sed -i 's/${{ env.OLD_VERSION }}/${{ env.NEW_VERSION }}/g' doc/conf.py
          sed -i 's/${{ env.OLD_VERSION }}/${{ env.NEW_VERSION }}/g' meson.build
          sed -i 's/${{ env.OLD_VERSION }}/${{ env.NEW_VERSION }}/g' pyproject.toml
          sed -i 's/${{ env.OLD_VERSION }}/${{ env.NEW_VERSION }}/g' skfmm/__init__.py
    - name: Create branch and commit changes
      run: |
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
         git checkout ${{ github.ref_name }}
         git add .
         git commit -m 'Update version'

    - name: Push changes
      run: git push origin ${{ github.ref_name }}
